# 프로퍼티즈 설정
#server.port=3000

#  yml 설정
server:
  port: 3000

# 프로퍼티즈 설정
#spring.application.name=day01
#spring.devtools.livereload.enabled=true

#  yml 설정
spring:
  application:
    name: "Day01"

  # 라이브리로드 설정
  devtools:
    livereload:
      enabled: true

  file:
    upload:
      path: # - : 리스트 형태의 값 = 키는 하나지만 값이 여러개이다 # file.upload.path
        - D:/uploads/
        - D:/uploads2/
      url: /uploads/ # file.upload.url