# 데이터베이스 설정
spring:
  # 데이터베이스_데이터소스 설정
  datasource:
    driver-class-name: org.h2.Driver
    # = driverClassName // 보통프로퍼티즈파일은 - 를 사용해야 함
    url: jdbc:h2:mem:test
    # db가 oracle이 아닐수도 있고 서버가 다를 수 있으니 이것도 바뀔 수 있는 부분이라 설정해주어야 함
    # 사실 이거는 환경변수로 설정할 수 있음 벗 연습할 때 헷갈릴까봐 이렇게함
    username : sa
    password:
    # 환경변수
    # username, password는 절대 드러나면 안됨(깃헙 등등)

  #JPA 설정(ORM, 쿼리를 알아서 만들어 준다)
  jpa:
    properties:
      hibernate:
        show_sql: true
        # sql이 보여야 개발하기 편함 -> 실행하는 sql을 콘솔에 출력
        format_sql: true
        # 실행되는 sql의 들여쓰기 및 줄 개행
        use_sql_comments: true
        # 자동생성해주는 쿼리에대한 주석

    hibernate:
      ddlAuto: create
      # 테이블생성, 제약조건 자동으로
      # -> 테이블 만들 필요x, 클래스에 정의만 해도 정의를 바탕으로 테이블 생성해줌
      # 테이블간 조인, fk 등등

# 로거 설정(로거는 기본 탑재되어 있음)
logging:
  level:
    org.hibernate.type: trace
    org.hibernate.orm.jdbc.bind: trace





